"""v1

Revision ID: eb72609dad2d
Revises: 
Create Date: 2025-05-01 21:28:27.714782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb72609dad2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VIPUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('notification', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VIPUsers_name'), 'VIPUsers', ['name'], unique=False)
    op.create_index(op.f('ix_VIPUsers_notification'), 'VIPUsers', ['notification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_VIPUsers_notification'), table_name='VIPUsers')
    op.drop_index(op.f('ix_VIPUsers_name'), table_name='VIPUsers')
    op.drop_table('VIPUsers')
    # ### end Alembic commands ###
